# .github/workflows/deploy.yml

name: Deploy Dream Vacation App

on:
  push:
    branches:
      - main  # Only run this workflow when pushing to main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push backend image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/dream-vacation-backend:latest ./backend
          docker push ${{ secrets.DOCKER_USERNAME }}/dream-vacation-backend:latest

      - name: Build and push frontend image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/dream-vacation-frontend:latest ./frontend
          docker push ${{ secrets.DOCKER_USERNAME }}/dream-vacation-frontend:latest

