# .github/workflows/deploy.yml
name: Deploy Dream Vacation App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push backend image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/dream-vacation-backend:latest ./backend
          docker push ${{ secrets.DOCKER_USERNAME }}/dream-vacation-backend:latest

      - name: Build and push frontend image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/dream-vacation-frontend:latest ./frontend
          docker push ${{ secrets.DOCKER_USERNAME }}/dream-vacation-frontend:latest

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/dream-vacation-backend:latest
            docker pull ${{ secrets.DOCKER_USERNAME }}/dream-vacation-frontend:latest
            docker-compose down
            docker-compose up -d
              docker system prune -f
              

            